// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOuxfffCs-rEGGSCbrxnF7GS7Y1KCLMjw',
    appId: '1:1082986286054:web:aa73a09328b6d8f4276427',
    messagingSenderId: '1082986286054',
    projectId: 'logtest-c902b',
    authDomain: 'logtest-c902b.firebaseapp.com',
    databaseURL: 'https://logtest-c902b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'logtest-c902b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChAz-uPctgz4lswrdjnRpNKlkbhLTP2Lk',
    appId: '1:1082986286054:android:15aaf82a4e769fee276427',
    messagingSenderId: '1082986286054',
    projectId: 'logtest-c902b',
    databaseURL: 'https://logtest-c902b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'logtest-c902b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTYjrehr38G_z5mgiEDCgC7AfMWBIHy8U',
    appId: '1:1082986286054:ios:de4616ec4578e4ef276427',
    messagingSenderId: '1082986286054',
    projectId: 'logtest-c902b',
    databaseURL: 'https://logtest-c902b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'logtest-c902b.appspot.com',
    iosBundleId: 'com.example.bigdataFrontendTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTYjrehr38G_z5mgiEDCgC7AfMWBIHy8U',
    appId: '1:1082986286054:ios:125fad866e374688276427',
    messagingSenderId: '1082986286054',
    projectId: 'logtest-c902b',
    databaseURL: 'https://logtest-c902b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'logtest-c902b.appspot.com',
    iosBundleId: 'com.example.bigdataFrontendTest.RunnerTests',
  );
}
